### ISSUE TITLE
Hidden files are copied also

### ISSUE THREAD

**Issue by StarPicard** [DecaTec/OCRmyPDF-script#1]
Hey, I just installed OCRmyPDF and used it with your script and it works great!
Thank You!

There's only one thing that doesn't work with my setup. My Input folder has some hidden files (Nextcloud), which should not be copied or deleted.

I'm already looking for a solution and would share it if You're interested.

**Comment by StarPicard** [comment]
Ok, I just removed 

```
shopt -s dotglob

shopt -u dotglob
```
and everything works. Issue solved ;)

**Comment by DecaTec** [comment]
So I'll close this one. Thanks for the input!
Maybe I can add a parameter that let's you decide on how to handle hidden files.
